In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a)
print(b)

[1 2 3 4 5]
[5 6 7 8 9]


In [3]:
type(a)

numpy.ndarray

### basic operations of array

In [4]:
print(a+b)
print(a-b)
print(a*b)

[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]


In [5]:
#creating a 2D Array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#shape of array
print(arr.shape)

(2, 3)


In [7]:
#creating a 3D array
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
#dimension of the array
print(arr.ndim)
print(arr2.ndim)

2
3


In [9]:
print(arr.dtype)

int64


In [10]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [12]:
np.arange(2,11)


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [14]:
np.random.randint(10,30, size=(3,3))

array([[19, 17, 18],
       [12, 17, 12],
       [14, 28, 11]], dtype=int32)

In [15]:
x = np.array([[7,2,3],[2,5,2],[3,5,1]])

y= np.array([[1,8,3],[3,7,2],[2,5,3]])

print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [16]:
print(x+y)
print(x-y)

[[ 8 10  6]
 [ 5 12  4]
 [ 5 10  4]]
[[ 6 -6  0]
 [-1 -2  0]
 [ 1  0 -2]]


In [17]:
#matrix multiplication

np.dot(x,y)

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [18]:
#matrix multiplication
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [19]:
x.prod()  #product all elements in the array

np.int64(12600)

In [20]:
x.mean() #mean of all element in the array

np.float64(3.3333333333333335)

In [21]:
round(y.mean())

4

In [22]:
y.mean(axis=1) #mean of each row

array([4.        , 4.        , 3.33333333])

In [23]:
x.mean(axis=0)  #mean of each coloumn

array([4., 4., 2.])

In [24]:
print(x.sum())
print(x.var())
print(x.std())

30
3.3333333333333335
1.8257418583505538


In [25]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [26]:
# print(b[0]) #FIRST ROW
# print(b[0,2]) #first row, third column
# print(b[-1]) #last row
# print(b[1:3]) #second and third row
# print(b[3:]) #last row

## array identification 

0D array = np.array(29)

1D array = np.array([26,30])  array of multiple 0D array

2D array = np.array([[1,2],[2,3]])

3D array = np.array([[[1,2],[2,3]],[3,4],[4,5]])